import { ActionItem, FinancialEntry, KPISubmission, MockUser, PendingApprovalSummary, UserRole } from "@/types";

export const mockUsers: MockUser[] = [
  {
    id: "acs",
    name: "Smt. Anjali Sharma",
    email: "anjali.sharma@hudd.ori",
    role: UserRole.ACS,
    department: "Housing & Urban Development Department",
    assignedSchemes: ["PMAY-U", "SUJALA", "GARIMA"],
  },
  {
    id: "ps",
    name: "Shri Pradeep Jena",
    email: "pradeep.jena@hudd.ori",
    role: UserRole.PS_HUDD,
    department: "Housing & Urban Development Department",
    assignedSchemes: ["All schemes"],
  },
  {
    id: "as",
    name: "Shri Suvendu Das",
    email: "suvendu.das@hudd.ori",
    role: UserRole.AS,
    department: "Housing & Urban Development Department",
    assignedSchemes: ["All schemes"],
  },
  {
    id: "fa",
    name: "Shri Rakesh Mohanty",
    email: "rakesh.mohanty@hudd.ori",
    role: UserRole.FA,
    department: "Finance & Planning",
    assignedSchemes: ["All schemes"],
  },
  {
    id: "tasu",
    name: "Ms. Priya Nair",
    email: "priya.nair@hudd.ori",
    role: UserRole.TASU,
    department: "Technical & Advisory Support Unit",
    assignedSchemes: ["PMAY-U", "SUJALA", "GARIMA"],
  },
  {
    id: "nodal",
    name: "Shri Amit Kumar",
    email: "amit.kumar@hudd.ori",
    role: UserRole.NODAL_OFFICER,
    department: "HUDD Field Unit",
    assignedSchemes: ["PMAY-U", "SUJALA", "GARIMA"],
  },
  {
    id: "director",
    name: "Shri B.K. Mishra",
    email: "bk.mishra@hudd.ori",
    role: UserRole.DIRECTOR,
    department: "Directorate of DMA",
    assignedSchemes: ["DMA", "All schemes"],
  },
  {
    id: "viewer",
    name: "Shri Ramesh Patnaik",
    email: "ramesh.patnaik@hudd.ori",
    role: UserRole.VIEWER,
    department: "Audit & Compliance",
    assignedSchemes: ["All schemes"],
  },
];

export const mockActionItems: ActionItem[] = [
  {
    id: "ai-01",
    title: "Release UFC tranches for Bhubaneswar sewerage works",
    description: "Unblock ₹280 Cr held due to compliance paperwork.",
    vertical: "UFC",
    priority: "Critical",
    dueDate: "2026-03-05",
    status: "OVERDUE",
    assignedTo: "Amit Kumar",
    reviewer: "Shri Suvendu Das",
    schemeId: "UFC-001",
    daysOverdue: 14,
    updates: [
      { timestamp: "2026-02-20", actor: "Amit Kumar", status: "IN_PROGRESS", note: "Field team following up" },
      { timestamp: "2026-02-28", actor: "Shri Suvendu Das", status: "UNDER_REVIEW", note: "Awaiting compliance review" },
    ],
    proofFiles: [{ name: "Compliance memo.pdf", link: "#" }],
  },
  {
    id: "ai-02",
    title: "Expedite PMAY fund release for high priority ULBs",
    description: "Cuttack, Berhampur, Rourkela, Sambalpur, Puri pending approvals.",
    vertical: "Housing",
    priority: "Critical",
    dueDate: "2026-03-10",
    status: "UNDER_REVIEW",
    assignedTo: "Ms. Priya Nair",
    reviewer: "Shri Suvendu Das",
    schemeId: "PMAY-U",
    updates: [
      { timestamp: "2026-03-01", actor: "Ms. Priya Nair", status: "IN_PROGRESS", note: "District returns compiled" },
    ],
    proofFiles: [],
  },
  {
    id: "ai-03",
    title: "Deploy TULIUP interns to 15 low-performing ULBs",
    description: "SAHAJOG profiling at 27% needs field acceleration.",
    vertical: "NULM",
    priority: "High",
    dueDate: "2026-03-15",
    status: "IN_PROGRESS",
    assignedTo: "Amit Kumar",
    reviewer: "Ms. Priya Nair",
    schemeId: "SAHAJOG",
    updates: [
      { timestamp: "2026-02-18", actor: "Amit Kumar", status: "OPEN", note: "Plan rolling out" },
    ],
    proofFiles: [],
  },
  {
    id: "ai-04",
    title: "Submit Q3 PMAY beneficiary data to MIS",
    description: "GoI reporting deadline approaching.",
    vertical: "Housing",
    priority: "High",
    dueDate: "2026-03-18",
    status: "PROOF_UPLOADED",
    assignedTo: "Ms. Priya Nair",
    reviewer: "Shri Amit Kumar",
    schemeId: "PMAY-U",
    updates: [
      { timestamp: "2026-03-10", actor: "Ms. Priya Nair", status: "PROOF_UPLOADED", note: "Files uploaded" },
    ],
    proofFiles: [{ name: "PMAY MIS upload.xlsx", link: "#" }],
  },
  {
    id: "ai-05",
    title: "Activate district coordinators for SBM acceleration",
    description: "Solid waste segregation lagging at 10.08%.",
    vertical: "SBM",
    priority: "High",
    dueDate: "2026-03-12",
    status: "IN_PROGRESS",
    assignedTo: "Amit Kumar",
    reviewer: "Ms. Priya Nair",
    schemeId: "SBM",
    updates: [],
    proofFiles: [],
  },
  {
    id: "ai-06",
    title: "Complete LED retrofit for Cuttack Zone-3",
    description: "Remaining 12% of brownfield retrofit in Zone-3.",
    vertical: "LED",
    priority: "Medium",
    dueDate: "2026-03-20",
    status: "OPEN",
    assignedTo: "Shri Amit Kumar",
    reviewer: "Ms. Priya Nair",
    schemeId: "LED",
    updates: [],
    proofFiles: [],
  },
  {
    id: "ai-07",
    title: "Grievance audit — flag 30+ day pending cases",
    description: "242 cases reviewed, 198 resolved.",
    vertical: "Grievance",
    priority: "Low",
    dueDate: "2026-03-25",
    status: "COMPLETED",
    assignedTo: "Shri Amit Kumar",
    reviewer: "Shri Suvendu Das",
    schemeId: "GRI-01",
    updates: [{ timestamp: "2026-03-01", actor: "Shri Amit Kumar", status: "COMPLETED", note: "Audit closed" }],
    proofFiles: [{ name: "Audit report.pdf", link: "#" }],
  },
  {
    id: "ai-08",
    title: "Clear Angul DPR backlog",
    description: "Unblock ₹120 Cr sewerage tranche.",
    vertical: "AMRUT",
    priority: "Medium",
    dueDate: "2026-03-22",
    status: "OPEN",
    assignedTo: "Ms. Priya Nair",
    reviewer: "Shri Suvendu Das",
    schemeId: "AMRUT",
    updates: [],
    proofFiles: [],
  },
  {
    id: "ai-09",
    title: "Launch urban mobility awareness sprint",
    description: "Focus on last-mile connectivity in Bhubaneswar.",
    vertical: "Mobility",
    priority: "High",
    dueDate: "2026-03-28",
    status: "OPEN",
    assignedTo: "Ms. Priya Nair",
    reviewer: "Shri Amit Kumar",
    schemeId: "CRUT",
    updates: [],
    proofFiles: [],
  },
  {
    id: "ai-10",
    title: "Expand SUJALA monitoring cells",
    description: "Fresh water quality testing in 12 ULBs.",
    vertical: "Water",
    priority: "Medium",
    dueDate: "2026-03-15",
    status: "IN_PROGRESS",
    assignedTo: "Amit Kumar",
    reviewer: "Shri Suvendu Das",
    schemeId: "SUJALA",
    updates: [],
    proofFiles: [],
  },
  {
    id: "ai-11",
    title: "Publish grievance dashboard to public portal",
    description: "Complete QA and publish.",
    vertical: "Grievance",
    priority: "Low",
    dueDate: "2026-03-30",
    status: "OPEN",
    assignedTo: "Ms. Priya Nair",
    reviewer: "Shri Amit Kumar",
    schemeId: "GRI-01",
    updates: [],
    proofFiles: [],
  },
  {
    id: "ai-12",
    title: "Institute literacy programme for SUJALA",
    description: "Train 250 field staff in water safe practices.",
    vertical: "Water",
    priority: "High",
    dueDate: "2026-03-27",
    status: "OPEN",
    assignedTo: "Ms. Priya Nair",
    reviewer: "Shri Suvendu Das",
    schemeId: "SUJALA",
    updates: [],
    proofFiles: [],
  },
  {
    id: "ai-13",
    title: "Finalize DMA GIS baseline",
    description: "Geotag 40 neighbourhood clusters.",
    vertical: "DMA",
    priority: "Critical",
    dueDate: "2026-03-09",
    status: "OVERDUE",
    assignedTo: "Amit Kumar",
    reviewer: "Shri Suvendu Das",
    schemeId: "DMA",
    daysOverdue: 1,
    updates: [{ timestamp: "2026-03-08", actor: "Amit Kumar", status: "IN_PROGRESS", note: "Mapping team mobilized" }],
    proofFiles: [],
  },
  {
    id: "ai-14",
    title: "Approve new ULIP proposals",
    description: "Critical to unlock ₹95 Cr.",
    vertical: "ULB",
    priority: "Critical",
    dueDate: "2026-03-18",
    status: "UNDER_REVIEW",
    assignedTo: "Amit Kumar",
    reviewer: "Ms. Priya Nair",
    schemeId: "ULB",
    updates: [],
    proofFiles: [],
  },
  {
    id: "ai-15",
    title: "Refresh SWM baseline for coastal ULBs",
    description: "Baseline due for coastal SBMs.",
    vertical: "SBM",
    priority: "High",
    dueDate: "2026-03-21",
    status: "OPEN",
    assignedTo: "Ms. Priya Nair",
    reviewer: "Shri Amit Kumar",
    schemeId: "SBM",
    updates: [],
    proofFiles: [],
  },
];

export const mockKPISubmissions: KPISubmission[] = [
  {
    id: "kpi-pmay-out1",
    scheme: "PMAY-U",
    vertical: "Housing",
    category: "CENTRAL",
    description: "Houses with basic services delivered",
    type: "OUTCOME",
    unit: "households",
    numerator: 8200,
    denominator: 12000,
    status: "approved",
    lastUpdated: "2026-03-18",
  },
  {
    id: "kpi-pmay-out2",
    scheme: "PMAY-U",
    vertical: "Housing",
    category: "CENTRAL",
    description: "Beneficiary satisfaction (post-handover)",
    type: "OUTPUT",
    unit: "%",
    numerator: 88,
    denominator: 100,
    status: "submitted_pending",
    lastUpdated: "2026-03-19",
    remarks: "Awaiting AS review",
  },
  {
    id: "kpi-pmay-out3",
    scheme: "PMAY-U",
    vertical: "Housing",
    category: "CENTRAL",
    description: "New shramik clusters certified",
    type: "OUTPUT",
    unit: "clusters",
    numerator: null,
    denominator: null,
    status: "not_submitted",
    lastUpdated: "2026-03-02",
  },
  {
    id: "kpi-sujala-out1",
    scheme: "SUJALA",
    vertical: "Water",
    category: "STATE",
    description: "Households reached by water quality testing",
    type: "OUTPUT",
    unit: "households",
    numerator: 4200,
    denominator: 5000,
    status: "submitted",
    lastUpdated: "2026-03-14",
  },
  {
    id: "kpi-sujala-out2",
    scheme: "SUJALA",
    vertical: "Water",
    category: "STATE",
    description: "Pipeline leakage incidents reduced",
    type: "OUTPUT",
    unit: "incidents",
    numerator: null,
    denominator: null,
    status: "not_submitted",
    lastUpdated: "2026-03-01",
  },
  {
    id: "kpi-sujala-out3",
    scheme: "SUJALA",
    vertical: "Water",
    category: "STATE",
    description: "Water quality index compliance",
    type: "OUTCOME",
    unit: "%",
    numerator: 94,
    denominator: 100,
    status: "submitted",
    lastUpdated: "2026-03-15",
  },
  {
    id: "kpi-sujala-out4",
    scheme: "SUJALA",
    vertical: "Water",
    category: "STATE",
    description: "Schools with clean drinking water",
    type: "OUTPUT",
    unit: "schools",
    numerator: null,
    denominator: null,
    status: "not_submitted",
    lastUpdated: "2026-02-25",
  },
  {
    id: "kpi-garima-out1",
    scheme: "GARIMA",
    vertical: "SBM",
    category: "STATE",
    description: "Doorstep waste collection contract signed",
    type: "OUTPUT",
    unit: "ULBs",
    numerator: null,
    denominator: null,
    status: "not_submitted",
    lastUpdated: "2026-03-05",
  },
  {
    id: "kpi-garima-out2",
    scheme: "GARIMA",
    vertical: "SBM",
    category: "STATE",
    description: "Waste processing facility reporting",
    type: "OUTCOME",
    unit: "tonnes",
    numerator: null,
    denominator: null,
    status: "not_submitted",
    lastUpdated: "2026-03-07",
  },
];

export const mockFinancialEntries: FinancialEntry[] = [
  { id: "fin-01", scheme: "PMAY-U", vertical: "Housing", status: "submitted_pending", annualBudget: 820, so: 320.5, ifms: 83.5, lastUpdated: "2026-03-17", locked: false, submitter: "Shri Rakesh Mohanty" },
  { id: "fin-02", scheme: "SUJALA", vertical: "Water", status: "submitted_pending", annualBudget: 360, so: 142.2, ifms: 136.8, lastUpdated: "2026-03-18", locked: false, submitter: "Shri Rakesh Mohanty" },
  { id: "fin-03", scheme: "GARIMA", vertical: "SBM", status: "submitted_this_week", annualBudget: 80, so: 35.0, ifms: 21.4, lastUpdated: "2026-03-20", locked: false, submitter: "Shri Rakesh Mohanty" },
  { id: "fin-04", scheme: "AMRUT 2.0 Water", vertical: "AMRUT", status: "draft", annualBudget: 680, so: 330.0, ifms: 320.0, lastUpdated: "2026-03-13", locked: false, submitter: "" },
  { id: "fin-05", scheme: "LED Brownfield", vertical: "LED", status: "draft", annualBudget: 100, so: 50.2, ifms: 48.7, lastUpdated: "2026-03-15", locked: false, submitter: "" },
  { id: "fin-06", scheme: "SBM Solid Waste", vertical: "SBM", status: "overdue", annualBudget: 220, so: 75.2, ifms: 60.0, lastUpdated: "2026-03-04", locked: false, submitter: "" },
  { id: "fin-07", scheme: "PMAY-U Sewerage", vertical: "Housing", status: "overdue", annualBudget: 240, so: 120.0, ifms: 110.4, lastUpdated: "2026-03-06", locked: false, submitter: "" },
  { id: "fin-08", scheme: "MSBY Infrastructure", vertical: "MSBY", status: "submitted_this_week", annualBudget: 340, so: 210.0, ifms: 198.0, lastUpdated: "2026-03-20", locked: false, submitter: "Shri Rakesh Mohanty" },
  { id: "fin-09", scheme: "SAHAJOG Profiling", vertical: "NULM", status: "submitted_pending", annualBudget: 120, so: 47.5, ifms: 45.0, lastUpdated: "2026-03-19", locked: false, submitter: "" },
  { id: "fin-10", scheme: "Capacity Building", vertical: "SUDA", status: "not_started", annualBudget: 88, so: 0, ifms: 0, lastUpdated: "2026-03-01", locked: false, submitter: "" },
];

export const pendingApprovalSummaries: PendingApprovalSummary[] = [
  { role: UserRole.ACS, financial: 3, kpi: 5, actionItems: 2 },
  { role: UserRole.PS_HUDD, financial: 3, kpi: 5, actionItems: 2 },
  { role: UserRole.AS, financial: 3, kpi: 5, actionItems: 2 },
  { role: UserRole.VIEWER, financial: 0, kpi: 0, actionItems: 0 },
];
