export const financialData = [
  { type: "State Sector Scheme", budget: 4365.0, so: 2689.25, ifms: 2311.57, pct: 52.96 },
  { type: "Centrally Sponsored Scheme", budget: 2164.0, so: 1196.57, ifms: 752.56, pct: 34.78 },
  { type: "State Finance Commission", budget: 1489.78, so: 1237.71, ifms: 1237.71, pct: 83.08 },
  { type: "Union Finance Commission", budget: 1069.66, so: 60.41, ifms: 60.41, pct: 5.65 },
  { type: "Other Transfer (Stamp Duty)", budget: 130.19, so: 129.68, ifms: 97.64, pct: 75.0 },
  { type: "Admin Expenditure", budget: 688.93, so: 0, ifms: 336.95, pct: 48.91 },
];

export const totalBudget = { budget: 9882.56, so: 5313.62, ifms: 4796.84, pct: 48.54 };

export const verticals = [
  {
    id: "water",
    name: "SUJALA / WATCO",
    icon: "💧",
    schemes: ["24×7 Water Supply", "OWSC", "Sewerage & Drainage"],
    budget: 1820.0,
    ifms: 892.4,
    pct: 49.0,
    target: 75,
    status: "warning",
    kpi: "68% households with tap water",
    trend: [30, 35, 38, 41, 45, 49],
  },
  {
    id: "swm",
    name: "Swachha Odisha / SBM",
    icon: "♻️",
    schemes: ["Solid Waste Mgmt", "Liquid Waste Mgmt", "GARIMA"],
    budget: 420.0,
    ifms: 42.3,
    pct: 10.08,
    target: 60,
    status: "critical",
    kpi: "42% SWM coverage",
    trend: [5, 6, 7, 8, 9, 10],
  },
  {
    id: "msby",
    name: "MSBY",
    icon: "🏗️",
    schemes: ["Infrastructure Dev", "Wage Employment", "Water Bodies"],
    budget: 680.0,
    ifms: 381.2,
    pct: 56.1,
    target: 70,
    status: "warning",
    kpi: "61% projects on track",
    trend: [28, 35, 40, 46, 52, 56],
  },
  {
    id: "mobility",
    name: "Urban Mobility / CRUT",
    icon: "🚌",
    schemes: ["Urban Road Transport", "PM e-Bus", "OMRT"],
    budget: 340.0,
    ifms: 218.6,
    pct: 64.3,
    target: 70,
    status: "warning",
    kpi: "Fleet utilisation 71%",
    trend: [48, 52, 55, 58, 61, 64],
  },
  {
    id: "housing",
    name: "Housing / OUHM",
    icon: "🏠",
    schemes: ["PMAY", "Awas Bandhu", "Urban Bandhu"],
    budget: 1240.0,
    ifms: 126.4,
    pct: 10.19,
    target: 60,
    status: "critical",
    kpi: "12,840 houses sanctioned",
    trend: [3, 4, 5, 7, 9, 10],
  },
  {
    id: "led",
    name: "LED Street Light",
    icon: "💡",
    schemes: ["Brownfield Retrofitting", "Greenfield"],
    budget: 180.0,
    ifms: 126.0,
    pct: 70.0,
    target: 80,
    status: "on-track",
    kpi: "78% retrofitted",
    trend: [40, 48, 54, 60, 66, 70],
  },
  {
    id: "nulm",
    name: "SAHAJOG / NULM",
    icon: "👥",
    schemes: ["Household Profiling", "Scheme Linkage", "PMAY Linkage"],
    budget: 290.0,
    ifms: 78.8,
    pct: 27.16,
    target: 60,
    status: "critical",
    kpi: "27.16% households profiled",
    trend: [8, 10, 13, 17, 22, 27],
  },
  {
    id: "amrut",
    name: "AMRUT 2.0",
    icon: "🌊",
    schemes: ["Water Infrastructure", "Sewerage Infrastructure"],
    budget: 1180.0,
    ifms: 611.0,
    pct: 51.8,
    target: 70,
    status: "warning",
    kpi: "54% project completion",
    trend: [22, 30, 36, 42, 48, 52],
  },
  {
    id: "capacity",
    name: "Capacity Building / SUDA",
    icon: "📚",
    schemes: ["Training", "Resource Mgmt", "TULIUP Interns"],
    budget: 88.0,
    ifms: 62.3,
    pct: 70.8,
    target: 80,
    status: "on-track",
    kpi: "94 sessions completed",
    trend: [44, 52, 58, 62, 67, 71],
  },
  {
    id: "bda",
    name: "Samruddha Sahara / BDA",
    icon: "🏙️",
    schemes: ["Town Planning", "Cities as Growth Hubs", "New City"],
    budget: 460.0,
    ifms: 264.5,
    pct: 57.5,
    target: 70,
    status: "warning",
    kpi: "1,240 ha planned",
    trend: [30, 36, 42, 48, 53, 58],
  },
  {
    id: "grievance",
    name: "Grievance Redressal",
    icon: "📋",
    schemes: ["ULB Grievance Portal"],
    budget: 0,
    ifms: 0,
    pct: 72.0,
    target: 100,
    status: "warning",
    kpi: "72% resolved (target 100%)",
    trend: [50, 56, 60, 64, 68, 72],
  },
  {
    id: "ddn",
    name: "DDN Integration",
    icon: "🔗",
    schemes: ["Door-to-Door Number"],
    budget: 0,
    ifms: 0,
    pct: 61.0,
    target: 100,
    status: "warning",
    kpi: "61% DDN matched with SUJOG",
    trend: [20, 30, 40, 50, 55, 61],
  },
];

export const schemes = [
  { name: "PMAY-U", vertical: "Housing", budget: 820.0, so: 320.5, ifms: 83.5, pct: 10.19, status: "critical" },
  { name: "Awas Bandhu", vertical: "Housing", budget: 280.0, so: 140.2, ifms: 28.0, pct: 10.0, status: "critical" },
  { name: "24×7 Water Supply", vertical: "Water", budget: 980.0, so: 542.0, ifms: 489.0, pct: 49.9, status: "warning" },
  { name: "AMRUT 2.0 Water", vertical: "AMRUT", budget: 680.0, so: 380.0, ifms: 352.0, pct: 51.8, status: "warning" },
  { name: "AMRUT 2.0 Sewerage", vertical: "AMRUT", budget: 500.0, so: 260.0, ifms: 259.0, pct: 51.8, status: "warning" },
  { name: "SBM Solid Waste", vertical: "SBM", budget: 220.0, so: 40.0, ifms: 22.2, pct: 10.08, status: "critical" },
  { name: "SBM Liquid Waste", vertical: "SBM", budget: 120.0, so: 18.0, ifms: 12.1, pct: 10.08, status: "critical" },
  { name: "GARIMA", vertical: "SBM", budget: 80.0, so: 8.0, ifms: 8.0, pct: 10.0, status: "critical" },
  { name: "CRUT Urban Bus", vertical: "Mobility", budget: 180.0, so: 120.0, ifms: 116.0, pct: 64.4, status: "warning" },
  { name: "PM e-Bus", vertical: "Mobility", budget: 100.0, so: 65.0, ifms: 62.0, pct: 62.0, status: "warning" },
  { name: "LED Brownfield", vertical: "LED", budget: 100.0, so: 80.0, ifms: 72.0, pct: 72.0, status: "on-track" },
  { name: "LED Greenfield", vertical: "LED", budget: 80.0, so: 60.0, ifms: 54.0, pct: 67.5, status: "warning" },
  { name: "SAHAJOG Profiling", vertical: "NULM", budget: 120.0, so: 40.0, ifms: 32.6, pct: 27.2, status: "critical" },
  { name: "NULM Livelihoods", vertical: "NULM", budget: 100.0, so: 30.0, ifms: 27.2, pct: 27.2, status: "critical" },
  { name: "MSBY Infrastructure", vertical: "MSBY", budget: 340.0, so: 220.0, ifms: 194.0, pct: 57.1, status: "warning" },
  { name: "MSBY Water Bodies", vertical: "MSBY", budget: 180.0, so: 100.0, ifms: 98.0, pct: 54.4, status: "warning" },
  { name: "UFC Water", vertical: "UFC", budget: 480.0, so: 28.0, ifms: 28.0, pct: 5.83, status: "critical" },
  { name: "UFC Sewerage", vertical: "UFC", budget: 380.0, so: 22.0, ifms: 22.0, pct: 5.79, status: "critical" },
  { name: "SFC Urban Roads", vertical: "SFC", budget: 620.0, so: 520.0, ifms: 520.0, pct: 83.9, status: "on-track" },
  { name: "BDA Town Planning", vertical: "BDA", budget: 240.0, so: 140.0, ifms: 138.0, pct: 57.5, status: "warning" },
  { name: "Capacity Building", vertical: "SUDA", budget: 88.0, so: 66.0, ifms: 62.3, pct: 70.8, status: "on-track" },
];

export const actionPoints = [
  {
    id: 1, title: "Release UFC tranches for Bhubaneswar sewerage works",
    officer: "CE WATCO", vertical: "UFC", deadline: "2026-01-31", status: "overdue",
    daysOverdue: 48, priority: "critical", description: "Unblock ₹280 Cr held due to compliance paperwork",
  },
  {
    id: 2, title: "Expedite PMAY fund release for 5 priority ULBs",
    officer: "MC-BDA", vertical: "Housing", deadline: "2026-02-10", status: "overdue",
    daysOverdue: 38, priority: "critical", description: "Cuttack, Berhampur, Rourkela, Sambalpur, Puri pending",
  },
  {
    id: 3, title: "Deploy TULIUP interns to 15 low-performing ULBs",
    officer: "Dir. SUDA", vertical: "NULM", deadline: "2026-02-15", status: "overdue",
    daysOverdue: 33, priority: "high", description: "SAHAJOG profiling at 27% needs field acceleration",
  },
  {
    id: 4, title: "Emergency review meeting — WATCO & CE re: UFC utilisation",
    officer: "Addl. Sec.", vertical: "UFC", deadline: "2026-02-20", status: "in-progress",
    daysOverdue: 0, priority: "critical", description: "UFC at 5.65% with FY-end 45 days away",
  },
  {
    id: 5, title: "Activate district coordinators — SBM push in bottom 10 ULBs",
    officer: "Dir. SBM", vertical: "SBM", deadline: "2026-01-15", status: "overdue",
    daysOverdue: 64, priority: "high", description: "SBM at 10.08%, solid waste segregation lagging",
  },
  {
    id: 6, title: "Submit EFC for new PMAY allocation",
    officer: "FA HUDD", vertical: "Housing", deadline: "2026-03-01", status: "in-progress",
    daysOverdue: 0, priority: "high", description: "Cabinet approval pending for enhanced allocation",
  },
  {
    id: 7, title: "Complete LED retrofit for Cuttack Zone-3",
    officer: "EE Cuttack", vertical: "LED", deadline: "2026-03-15", status: "in-progress",
    daysOverdue: 0, priority: "medium", description: "Last 12% of brownfield retrofitting in zone-3",
  },
  {
    id: 8, title: "Upload Q3 PMAY beneficiary data to MIS",
    officer: "Dir. OUHM", vertical: "Housing", deadline: "2026-02-28", status: "pending",
    daysOverdue: 0, priority: "medium", description: "GoI reporting deadline approaching",
  },
  {
    id: 9, title: "AMRUT 2.0 — DPR approval for Angul sewerage",
    officer: "CE AMRUT", vertical: "AMRUT", deadline: "2026-03-10", status: "pending",
    daysOverdue: 0, priority: "medium", description: "DPR submitted, technical committee review pending",
  },
  {
    id: 10, title: "Grievance audit — flag 30+ day pending cases",
    officer: "Dir. Governance", vertical: "Grievance", deadline: "2026-03-05", status: "completed",
    daysOverdue: 0, priority: "low", description: "242 cases reviewed, 198 resolved",
  },
];

export const nbaRecommendations = [
  {
    id: 1,
    priority: "critical",
    scheme: "UFC / WATCO",
    action: "Emergency tranche release for sewerage works — ₹280 Cr blocked",
    officer: "CE WATCO + FA HUDD",
    impact: "+18 pct points UFC utilisation",
    evidence: "UFC at 5.65% with 11 days to quarter-end. Zero disbursals since Dec 15.",
    deadline: "2026-03-25",
  },
  {
    id: 2,
    priority: "critical",
    scheme: "PMAY-U / Housing",
    action: "Coordinate GoI/GoO fund release for Cuttack, Berhampur, Rourkela",
    officer: "MC-BDA + Finance Dept",
    impact: "+8 pct points PMAY utilisation (₹65 Cr)",
    evidence: "PMAY at 10.19%. 3,200 sanctioned houses awaiting first-instalment disbursal.",
    deadline: "2026-03-28",
  },
  {
    id: 3,
    priority: "high",
    scheme: "SBM / Swachha Odisha",
    action: "Activate district coordinators in bottom 10 ULBs for SWM infrastructure push",
    officer: "Dir. SBM + District Collectors",
    impact: "+12 pct points SBM utilisation before FY close",
    evidence: "SBM at 10.08%. Q4 acceleration historically yields 2.4× spend velocity.",
    deadline: "2026-03-22",
  },
  {
    id: 4,
    priority: "high",
    scheme: "SAHAJOG / NULM",
    action: "Deploy 45 TULIUP interns to 15 low-performing ULBs for door-to-door surveys",
    officer: "Dir. SUDA",
    impact: "+15 pct points household profiling coverage",
    evidence: "At 27.16% with 42% of target ULBs untouched. Intern deployment historically yields 3× profiling velocity.",
    deadline: "2026-03-25",
  },
  {
    id: 5,
    priority: "medium",
    scheme: "AMRUT 2.0",
    action: "Clear Angul DPR backlog — unblock ₹120 Cr sewerage tranche",
    officer: "CE AMRUT",
    impact: "+10 pct points AMRUT utilisation",
    evidence: "5 DPRs pending technical clearance for >30 days. GoI deadline: April 5.",
    deadline: "2026-03-30",
  },
];

export const monthlySpend = [
  { month: "Apr", actual: 180, forecast: 220 },
  { month: "May", actual: 310, forecast: 320 },
  { month: "Jun", actual: 420, forecast: 450 },
  { month: "Jul", actual: 520, forecast: 560 },
  { month: "Aug", actual: 680, forecast: 700 },
  { month: "Sep", actual: 820, forecast: 850 },
  { month: "Oct", actual: 980, forecast: 1000 },
  { month: "Nov", actual: 1180, forecast: 1200 },
  { month: "Dec", actual: 1420, forecast: 1450 },
  { month: "Jan", actual: 1640, forecast: 1700 },
  { month: "Feb", actual: null, forecast: 1980 },
  { month: "Mar", actual: null, forecast: 2480 },
];

export const ulbPerformance = [
  { ulb: "Bhubaneswar", pmay: 24, sbm: 18, water: 72, grievance: 89, overall: 51 },
  { ulb: "Cuttack", pmay: 12, sbm: 8, water: 58, grievance: 71, overall: 37 },
  { ulb: "Rourkela", pmay: 9, sbm: 11, water: 61, grievance: 68, overall: 37 },
  { ulb: "Berhampur", pmay: 7, sbm: 6, water: 44, grievance: 55, overall: 28 },
  { ulb: "Sambalpur", pmay: 15, sbm: 22, water: 66, grievance: 78, overall: 45 },
  { ulb: "Puri", pmay: 18, sbm: 14, water: 70, grievance: 82, overall: 46 },
  { ulb: "Baripada", pmay: 4, sbm: 5, water: 38, grievance: 42, overall: 22 },
  { ulb: "Balasore", pmay: 6, sbm: 9, water: 42, grievance: 48, overall: 26 },
];

export const chatHistory: Array<{ role: "user" | "assistant"; content: string }> = [
  {
    role: "assistant",
    content: "HUDD NEXUS is online. I have real-time visibility across ₹9,882 Cr in budgets, 33 schemes, and 114 ULBs. What would you like to know?",
  },
];

export const suggestedQueries = [
  "What is the expenditure status of UFC today?",
  "Which ULBs are worst on grievance resolution?",
  "Will PMAY funds lapse this year?",
  "Show overdue action points",
  "AMRUT 2.0 completion forecast",
  "Top 5 schemes by lapse risk",
];
